name: macOS Remote Desktop (VNC via Tailscale)

on:
  # Bu iş akışını GitHub arayüzünden manuel olarak başlatmanızı sağlar
  workflow_dispatch:

jobs:
  secure-vnc:
    runs-on: macos-latest 
    timeout-minutes: 3600 

    steps:
      - name: Configure User and Enable VNC (Remote Desktop)
        run: |
          USERNAME="RDP"
          # KULLANICI ŞİFRESİ: Güvenlik için daha güçlü şifre korundu.
          PASSWORD="Ehe.1234" 
          
          echo "Setting up user '$USERNAME' with password '$PASSWORD'."
          
          # 1. Kullanıcıyı oluşturma
          LAST_ID=$(dscl . list /Users UniqueID | awk '{print $2}' | sort -n | tail -1)
          NEW_ID=$((LAST_ID + 1))
          
          sudo dscl . create /Users/$USERNAME
          sudo dscl . create /Users/$USERNAME UniqueID $NEW_ID
          sudo dscl . create /Users/$USERNAME PrimaryGroupID 20
          sudo dscl . create /Users/$USERNAME UserShell /bin/bash
          sudo dscl . create /Users/$USERNAME RealName "GH Remote User"
          sudo dscl . create /Users/$USERNAME NFSHomeDirectory /Users/$USERNAME
          sudo dscl . passwd /Users/$USERNAME "$PASSWORD"
          sudo mkdir -p /Users/$USERNAME
          sudo chown $USERNAME:staff /Users/$USERNAME
          sudo dscl . append /Groups/admin GroupMembership $USERNAME
          
          # 2. VNC (Ekran Paylaşımı) Özelliğini Etkinleştirme (Düzeltildi)
          echo "Enabling VNC and setting permissions using kickstart..."
          
          # Bilgisayarın uykuya geçmesini engellemek için daha basit komut
          sudo pmset -a disablesleep 1
          
          # Ekran paylaşımını etkinleştirir ve kullanıcıya tüm yetkileri verir.
          # Bu komutun çalıştığı önceki çıktınızda görüldü.
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users "$USERNAME" -privs -all -restart -agent
          
          # VNC sunucusunun tam ekran kontrolüne izin verdiğinden emin olma
          sudo defaults write com.apple.ScreenSharing AllowAnyUser -bool YES
          
          echo "VNC (Remote Desktop equivalent) is now enabled and configured."
          echo "RDP_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV
          
      - name: Install Tailscale and Start Service
        run: |
          export PATH="/opt/homebrew/bin:$PATH" 
          export PATH="/usr/local/bin:$PATH"
          
          if ! brew install tailscale; then
              echo "Tailscale kurulumu başarısız oldu."
              exit 1
          fi

          echo "Starting tailscaled service..."
          sudo tailscaled &
          sleep 5

      - name: Establish Tailscale Connection
        run: |
          export PATH="/opt/homebrew/bin:$PATH" 
          export PATH="/usr/local/bin:$PATH"
          
          echo "Connecting to Tailscale network..."
          tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-macos-vnc-$GITHUB_RUN_ID
          
          # Tailscale IP almasını bekleme
          TS_IP=""
          for i in {1..15}; do
              TS_IP=$(tailscale ip -4 2>/dev/null)
              if [ -n "$TS_IP" ]; then
                  break
              fi
              sleep 4
          done
          
          if [ -z "$TS_IP" ]; then
              echo "Tailscale IP adresi alınamadı. İşlem başarısız."
              exit 1
          fi
          
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
      
      - name: Maintain Connection and Display Info
        run: |
          echo "
          
          ==================================
              MAC GRAFİK ARAYÜZÜ (VNC) ERİŞİMİ
          ==================================
          
          Adres (Tailscale IP): $TAILSCALE_IP
          Kullanıcı Adı: RDP
          Şifre: Ehe.1234
          
          BAĞLANTI ŞEKLİ: Windows'ta VNC İstemcisi
          
          1. Windows'ta RealVNC Viewer, TightVNC Viewer gibi bir VNC istemcisi açın.
          2. Adres olarak: $TAILSCALE_IP girin.
          3. Kullanıcı adı/Şifre olarak RDP / Ehe.1234 kullanın.
          
          ==================================
          "
          # Çalıştırıcıyı aktif tutmak için uzun süre döngüde kal
          while true; do
              echo "[$(date)] VNC Erişimi Aktif. İş akışını sonlandırmak için manuel olarak iptal edin."
              sleep 300
          done
