- name: Configure User and Install TigerVNC
        run: |
          USERNAME="RDP"
          PASSWORD="Ehe.1234" 
          
          # ... (Kullanıcı oluşturma adımları aynı kalır) ...
          
          # 2. TigerVNC kurma
          echo "Installing TigerVNC Server (Xvnc) to avoid black screen issue..."
          export PATH="/opt/homebrew/bin:$PATH" 
          export PATH="/usr/local/bin:$PATH"
          
          brew install tiger-vnc
          
          # 3. VNC şifresini ayarlar (DÜZELTİLDİ: PATH eklendi)
          echo "Setting VNC password file for $USERNAME."
          
          # Homebrew PATH'ini (arm64 için /opt/homebrew/bin) RDP kullanıcısına aktararak komutun bulunmasını sağla.
          HOMEBREW_PATH="/opt/homebrew/bin"
          
          sudo su - $USERNAME -c "
            export PATH=$HOMEBREW_PATH:\$PATH
            mkdir -p ~/.vnc
            # vncpasswd artık bulunabilir.
            echo '$PASSWORD' | vncpasswd -f > ~/.vnc/passwd
            chmod 600 ~/.vnc/passwd
          "
          
          # 4. TigerVNC Sunucusunu Başlatma (DÜZELTİLDİ: PATH eklendi)
          echo "Starting TigerVNC server on display :1 (port 5901)."
          
          # Xvnc'nin tam yolu Homebrew PATH'ine göre ayarlanır.
          
          # Xvnc'yi belirtilen kullanıcı (RDP) altında başlat.
          sudo su - $USERNAME -c "
            export PATH=$HOMEBREW_PATH:\$PATH
            Xvnc :1 -geometry 1920x1080 -depth 24 -rfbauth /Users/$USERNAME/.vnc/passwd -desktop 'GitHub Runner' &
          "
          
          sleep 5
          
          echo "VNC Server (TigerVNC) is running on port 5901."
          echo "RDP_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV
