name: macOS Remote Desktop (VNC via Tailscale)

on:
  # İş akışını GitHub arayüzünden manuel olarak başlatmanızı sağlar
  workflow_dispatch:

jobs:
  secure-vnc:
    runs-on: macos-latest 
    timeout-minutes: 3600 

    steps:
      - name: Configure User and Install TigerVNC
        run: |
          USERNAME="RDP"
          PASSWORD="Ehe.1234" 
          
          echo "Setting up user '$USERNAME' with password '$PASSWORD'."
          
          # 1. Kullanıcıyı oluşturma
          LAST_ID=$(dscl . list /Users UniqueID | awk '{print $2}' | sort -n | tail -1)
          NEW_ID=$((LAST_ID + 1))
          
          sudo dscl . create /Users/$USERNAME
          sudo dscl . create /Users/$USERNAME UniqueID $NEW_ID
          sudo dscl . create /Users/$USERNAME PrimaryGroupID 20
          sudo dscl . create /Users/$USERNAME UserShell /bin/bash
          sudo dscl . create /Users/$USERNAME RealName "GH Remote User"
          sudo dscl . create /Users/$USERNAME NFSHomeDirectory /Users/$USERNAME
          sudo dscl . passwd /Users/$USERNAME "$PASSWORD"
          sudo mkdir -p /Users/$USERNAME
          sudo chown $USERNAME:staff /Users/$USERNAME
          sudo dscl . append /Groups/admin GroupMembership $USERNAME
          
          # 2. TigerVNC kurma
          echo "Installing TigerVNC Server (Xvnc) to avoid black screen issue..."
          export PATH="/opt/homebrew/bin:$PATH" 
          export PATH="/usr/local/bin:$PATH"
          
          brew install tiger-vnc
          
          # 3. VNC dosyalarını bulma ve kopyalama (KRİTİK DÜZELTME)
          USER_BIN_PATH="/usr/local/bin" 
          
          echo "Determining VNC binary paths for reliable execution..."

          # Cellar yolunu bulma (Örn: /opt/homebrew/Cellar/tiger-vnc/1.15.0/bin)
          TIGER_VNC_BIN_DIR=$(find /opt/homebrew/Cellar/tiger-vnc/ -maxdepth 2 -type d -name "bin" | head -n 1)

          # Hangi yoldan kopyalama yapılacağını belirle: 1. Cellar, 2. Homebrew bin (fallback)
          if [ -d "$TIGER_VNC_BIN_DIR" ] && [ -f "$TIGER_VNC_BIN_DIR/vncpasswd" ]; then
              SOURCE_PATH="$TIGER_VNC_BIN_DIR"
              echo "Source path (Cellar) found: $SOURCE_PATH"
          elif [ -f "/opt/homebrew/bin/vncpasswd" ]; then
              SOURCE_PATH="/opt/homebrew/bin"
              echo "Source path (Homebrew bin) found: $SOURCE_PATH"
          else
              echo "HATA: VNC ikili dosyaları için güvenilir kaynak bulunamadı. Kurulumu kontrol edin."
              exit 1
          fi
          
          echo "Copying VNC binaries from $SOURCE_PATH to $USER_BIN_PATH..."
          
          # Dosyaları /usr/local/bin'e kopyala (İzin/PATH sorununu çözer)
          sudo cp $SOURCE_PATH/vncpasswd $USER_BIN_PATH/
          sudo cp $SOURCE_PATH/Xvnc $USER_BIN_PATH/
          
          # Dosyaların çalıştırılabilir olduğundan emin ol
          sudo chmod +x $USER_BIN_PATH/vncpasswd
          sudo chmod +x $USER_BIN_PATH/Xvnc

          # Komutlar artık /usr/local/bin altında
          VNCPASSWD_CMD="$USER_BIN_PATH/vncpasswd"
          XVNC_CMD="$USER_BIN_PATH/Xvnc"
          
          # 4. VNC şifresini ayarlar
          echo "Setting VNC password file for $USERNAME."
          
          # RDP kullanıcısı altında vncpasswd komutunu çalıştır (PATH sorunu yok)
          sudo su - $USERNAME -c "
            mkdir -p ~/.vnc
            echo '$PASSWORD' | $VNCPASSWD_CMD -f > ~/.vnc/passwd
            chmod 600 ~/.vnc/passwd
          "
          
          # 5. TigerVNC Sunucusunu Başlatma
          echo "Starting TigerVNC server on display :1 (port 5901)."
          
          # RDP kullanıcısı altında Xvnc komutunu başlat (PATH/İzin sorunu yok)
          sudo su - $USERNAME -c "
            $XVNC_CMD :1 -geometry 1920x1080 -depth 24 -rfbauth /Users/$USERNAME/.vnc/passwd -desktop 'GitHub Runner' &
          "
          
          sleep 5
          
          echo "VNC Server (TigerVNC) is running on port 5901."
          echo "RDP_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV
          
      - name: Install Tailscale and Start Service
        run: |
          export PATH="/opt/homebrew/bin:$PATH" 
          export PATH="/usr/local/bin:$PATH"
          
          if ! brew install tailscale; then
              echo "Tailscale kurulumu başarısız oldu."
              exit 1
          fi

          echo "Starting tailscaled service..."
          sudo tailscaled &
          sleep 5

      - name: Establish Tailscale Connection
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          export PATH="/opt/homebrew/bin:$PATH" 
          export PATH="/usr/local/bin:$PATH"
          
          echo "Connecting to Tailscale network..."
          tailscale up --authkey=$TAILSCALE_AUTH_KEY --hostname=gh-macos-tigervnc-$GITHUB_RUN_ID
          
          # IP almasını bekleme
          TS_IP=""
          for i in {1..15}; do
              TS_IP=$(tailscale ip -4 2>/dev/null)
              if [ -n "$TS_IP" ]; then
                  break
              fi
              sleep 4
          done
          
          if [ -z "$TS_IP" ]; then
              echo "Tailscale IP adresi alınamadı. İşlem başarısız."
              exit 1
          fi
          
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
      
      - name: Maintain Connection and Display Info
        run: |
          echo "
          
          ==================================
              MAC GRAFİK ARAYÜZÜ (TIGER VNC) ERİŞİMİ
          ==================================
          
          Adres (Tailscale IP): $TAILSCALE_IP
          VNC Portu: 5901
          VNC Şifresi: Ehe.1234
          
          BAĞLANTI ŞEKLİ: **RealVNC Viewer** veya **TigerVNC Viewer**
          
          1. Adres olarak: **$TAILSCALE_IP:5901** girin.
          2. Sadece VNC şifresi istendiğinde: **Ehe.1234** kullanın.
          
          ==================================
          "
          # Çalıştırıcıyı aktif tutmak için uzun süre döngüde kal
          while true; do
              echo "[$(date)] VNC Erişimi Aktif. İş akışını sonlandırmak için manuel olarak iptal edin."
              sleep 300
          done
