on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-13
    timeout-minutes: 360

    steps:
      # ADIM 1: Sorun çıkarmayacak sabit bir şifre belirle
      - name: Set a Simple Password for Runner User
        run: |
          VNC_USER="runner"
          # Kimlik doğrulama hatasını önlemek için basit, özel karaktersiz bir şifre kullanıyoruz.
          VNC_PASS="GitHub12345"
          
          echo "VNC_USER=${VNC_USER}" >> $GITHUB_ENV
          echo "VNC_PASS=${VNC_PASS}" >> $GITHUB_ENV

          # sysadminctl ile şifreyi sıfırla
          sudo sysadminctl -resetPasswordFor $VNC_USER -newPassword "$VNC_PASS"
          
          echo "Password for user '$VNC_USER' has been set."

      # ADIM 2: VNC (Ekran Paylaşımı) servisini etkinleştir
      - name: Enable VNC for Runner User
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
              -activate -configure -access -on \
              -users ${{ env.VNC_USER }} -privs -all \
              -restart -agent -menu
          echo "VNC service enabled for user '${{ env.VNC_USER }}'."

      # ADIM 3: Tailscale'i kur ve başlat
      - name: Install and Start Tailscale
        run: |
          brew install tailscale
          sudo brew services start tailscale
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-macos-${{ github.run_id }} --accept-routes

      # ADIM 4: Tailscale IP adresini al
      - name: Get Tailscale IP
        run: |
          TS_IP=""
          for i in {1..10}; do
            TS_IP=$(tailscale ip -4)
            if [ -n "$TS_IP" ]; then
              echo "Tailscale IP address acquired: $TS_IP"
              break
            fi
            echo "Waiting for Tailscale IP... ($i/10)"
            sleep 5
          done

          if [ -z "$TS_IP" ]; then
            echo "::error::Could not get Tailscale IP address."
            exit 1
          fi
          
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      # ADIM 5: Bağlantıyı aktif tut ve bilgileri göster
      - name: Maintain Connection and Show Details
        run: |
          echo ""
          echo "==============================="
          echo "=== VNC BAĞLANTI BİLGİLERİ ==="
          echo "==============================="
          echo "Sunucu Adresi : ${{ env.TAILSCALE_IP }}"
          echo "Kullanıcı Adı : ${{ env.VNC_USER }}"
          echo "Şifre         : ${{ env.VNC_PASS }}"
          echo "==============================="
          echo ""
          
          while true; do
            echo "[$(date)] VNC oturumu aktif. Sonlandırmak için iş akışını iptal edin."
            sleep 300
          done
