- name: Configure User and Install TigerVNC
        run: |
          USERNAME="RDP"
          PASSWORD="Ehe.1234" 
          
          echo "Setting up user '$USERNAME' with password '$PASSWORD'."
          
          # ... (Kullanıcı oluşturma adımları aynı kalır) ...
          
          # 2. TigerVNC kurma
          echo "Installing TigerVNC Server (Xvnc) to avoid black screen issue..."
          export PATH="/opt/homebrew/bin:$PATH" 
          export PATH="/usr/local/bin:$PATH"
          
          brew install tiger-vnc
          
          # *** YENİ DÜZELTME BAŞLANGICI ***
          
          # Homebrew'in ikili dosyalarının bulunduğu yolu belirle (M1/M2/M3 için standart yol)
          HOMEBREW_BIN_PATH="/opt/homebrew/bin"

          # 3. VNC şifresini ayarlar
          echo "Setting VNC password file for $USERNAME."
          
          # PATH'i RDP kullanıcısının sudo su - komutuna doğrudan enjekte et
          sudo su - $USERNAME -c "
            export PATH=$HOMEBREW_BIN_PATH:\$PATH
            # Komutlar artık bulunmalı
            mkdir -p ~/.vnc
            echo '$PASSWORD' | vncpasswd -f > ~/.vnc/passwd
            chmod 600 ~/.vnc/passwd
          "
          
          # 4. TigerVNC Sunucusunu Başlatma
          echo "Starting TigerVNC server on display :1 (port 5901)."
          
          # Xvnc'yi belirtilen kullanıcı (RDP) altında başlat. 
          # PATH'i aynı şekilde enjekte et.
          sudo su - $USERNAME -c "
            export PATH=$HOMEBREW_BIN_PATH:\$PATH
            # Xvnc artık bulunmalı.
            Xvnc :1 -geometry 1920x1080 -depth 24 -rfbauth /Users/$USERNAME/.vnc/passwd -desktop 'GitHub Runner' &
          "
          
          sleep 5
          
          echo "VNC Server (TigerVNC) is running on port 5901."
          echo "RDP_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV
