- name: Configure User and Install TigerVNC
        run: |
          USERNAME="RDP"
          PASSWORD="Ehe.1234" 
          
          echo "Setting up user '$USERNAME' with password '$PASSWORD'."
          
          # 1. Kullanıcıyı oluşturma (Bu kısım aynı kalacak)
          LAST_ID=$(dscl . list /Users UniqueID | awk '{print $2}' | sort -n | tail -1)
          NEW_ID=$((LAST_ID + 1))
          
          sudo dscl . create /Users/$USERNAME
          sudo dscl . create /Users/$USERNAME UniqueID $NEW_ID
          sudo dscl . create /Users/$USERNAME PrimaryGroupID 20
          sudo dscl . create /Users/$USERNAME UserShell /bin/bash
          sudo dscl . create /Users/$USERNAME RealName "GH Remote User"
          sudo dscl . create /Users/$USERNAME NFSHomeDirectory /Users/$USERNAME
          sudo dscl . passwd /Users/$USERNAME "$PASSWORD"
          sudo mkdir -p /Users/$USERNAME
          sudo chown $USERNAME:staff /Users/$USERNAME
          sudo dscl . append /Groups/admin GroupMembership $USERNAME
          
          # 2. Sistem VNC yerine TigerVNC kurma (DÜZELTİLDİ: tiger-vnc)
          echo "Installing TigerVNC Server (Xvnc) to avoid black screen issue..."
          export PATH="/opt/homebrew/bin:$PATH" 
          export PATH="/usr/local/bin:$PATH"
          
          # HATA DÜZELTİLDİ: brew install tiger-vnc
          brew install tiger-vnc
          
          # 3. VNC şifresini TigerVNC için ayarlar
          mkdir -p /Users/$USERNAME/.vnc
          # VNC şifresi 8 karakterle sınırlıdır, bu yüzden sadece ilk 8 karakteri kullanır.
          # Ancak 'Ehe.1234' 8 karakter olduğu için sorun yok.
          echo "$PASSWORD" | vncpasswd -f > /Users/$USERNAME/.vnc/passwd
          sudo chown $USERNAME:staff /Users/$USERNAME/.vnc/passwd
          sudo chmod 600 /Users/$USERNAME/.vnc/passwd
          
          # 4. TigerVNC Sunucusunu Başlatma (Sanal Masaüstü Oturumu)
          echo "Starting TigerVNC server on display :1 (port 5901)."
          
          # Xvnc'yi belirtilen kullanıcı (RDP) altında başlat
          # Bu komutun PATH'te bulunabilmesi için tam yolu deneyebiliriz.
          # Homebrew /opt/homebrew/bin altına kurar.
          Xvnc_PATH=$(find /usr/local/Cellar/tiger-vnc/ -name Xvnc -print -quit)
          
          # Eğer Xvnc yolu bulunamazsa /opt/homebrew/bin veya /usr/local/bin altından çalıştırmayı deneriz.
          if [ -z "$Xvnc_PATH" ]; then
              Xvnc_CMD="Xvnc"
          else
              Xvnc_CMD="$Xvnc_PATH"
          fi
          
          # Xvnc'yi belirtilen kullanıcı (RDP) altında başlat
          sudo su - $USERNAME -c "$Xvnc_CMD :1 -geometry 1920x1080 -depth 24 -rfbauth /Users/$USERNAME/.vnc/passwd -localhost -query localhost -desktop 'GitHub Runner' &"
          
          # Servisin başlaması için bekle
          sleep 5
          
          echo "VNC Server (TigerVNC) is running on port 5901."
          echo "RDP_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV
