on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-13
    timeout-minutes: 360

    steps:
      - name: Set VNC Password for Existing Runner User
        run: |
          VNC_USER="runner"
          VNC_PASS=$(openssl rand -base64 16)
          
          echo "VNC_USER=${VNC_USER}" >> $GITHUB_ENV
          echo "VNC_PASS=${VNC_PASS}" >> $GITHUB_ENV

          # DÜZELTME: Parolayı komuta doğrudan vermek yerine pipe ile yönlendiriyoruz.
          echo "$VNC_PASS" | sudo dscl . -passwd /Users/$VNC_USER
          
          echo "Password set for user '$VNC_USER'."

      - name: Enable VNC (Screen Sharing) for Runner User
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
              -activate -configure -access -on \
              -users ${{ env.VNC_USER }} -privs -all \
              -restart -agent -menu
          echo "VNC service enabled for user '${{ env.VNC_USER }}'."

      - name: Install and Start Tailscale
        run: |
          brew install tailscale
          sudo brew services start tailscale
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-macos-${{ github.run_id }} --accept-routes

      - name: Get Tailscale IP
        run: |
          TS_IP=""
          for i in {1..10}; do
            TS_IP=$(tailscale ip -4)
            if [ -n "$TS_IP" ]; then
              echo "Tailscale IP address acquired: $TS_IP"
              break
            fi
            echo "Waiting for Tailscale IP... ($i/10)"
            sleep 5
          done

          if [ -z "$TS_IP" ]; then
            echo "::error::Could not get Tailscale IP address."
            exit 1
          fi
          
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Maintain Connection
        run: |
          echo ""
          echo "=== VNC CONNECTION DETAILS ==="
          echo "Server Address: ${{ env.TAILSCALE_IP }}"
          echo "Username      : ${{ env.VNC_USER }}"
          echo "Password      : ${{ env.VNC_PASS }}"
          echo "==============================="
          echo ""
          
          while true; do
            echo "[$(date)] VNC session is active. Cancel the workflow to terminate."
            sleep 300
          done
