name: macOS Remote Access (SSH via Tailscale)

on:
  workflow_dispatch:

jobs:
  secure-ssh:
    runs-on: macos-latest 
    timeout-minutes: 3600 

    steps:
      - name: Configure SSH Access and Create User
        run: |
          # 1. Uzak Girişi (SSH) Etkinleştirme
          sudo systemsetup -setremotelogin on
          
          # 2. Yeni Kullanıcı Oluşturma
          USERNAME="RDP"
          # GÜVENLİK DÜZELTMESİ: macOS'un kabul edeceği güçlü şifre
          PASSWORD="Ehe.1234" 
          
          echo "Setting up user '$USERNAME' with password '$PASSWORD'."
          
          LAST_ID=$(dscl . list /Users UniqueID | awk '{print $2}' | sort -n | tail -1)
          NEW_ID=$((LAST_ID + 1))
          
          # Kullanıcıyı oluşturma ve gerekli ayarları yapma
          sudo dscl . create /Users/$USERNAME
          sudo dscl . create /Users/$USERNAME UniqueID $NEW_ID
          sudo dscl . create /Users/$USERNAME PrimaryGroupID 20
          sudo dscl . create /Users/$USERNAME UserShell /bin/bash
          sudo dscl . create /Users/$USERNAME RealName "GH Remote User"
          sudo dscl . create /Users/$USERNAME NFSHomeDirectory /Users/$USERNAME
          
          # Şifreyi ayarla
          sudo dscl . passwd /Users/$USERNAME "$PASSWORD"
          
          # Home dizinini oluştur ve izinleri ayarla
          sudo mkdir -p /Users/$USERNAME
          sudo chown $USERNAME:staff /Users/$USERNAME
          
          # Admin yetkisi verme
          sudo dscl . append /Groups/admin GroupMembership $USERNAME
          
          echo "RDP_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV
          
      - name: Install Tailscale and Start Service
        run: |
          # PATH'i ayarla
          export PATH="/opt/homebrew/bin:$PATH" 
          export PATH="/usr/local/bin:$PATH"
          
          echo "Attempting to install Tailscale via Homebrew..."
          if ! brew install tailscale; then
              echo "Homebrew ile kurulum başarısız oldu."
              exit 1
          fi

          # Servisi başlat
          echo "Starting tailscaled service..."
          # Servisi arka planda çalıştırmak için 'sudo' ile çağır
          sudo tailscaled &
          
          sleep 5
          echo "Tailscale service started."

      - name: Establish Tailscale Connection
        run: |
          # PATH'i ayarla
          export PATH="/opt/homebrew/bin:$PATH" 
          export PATH="/usr/local/bin:$PATH"
          
          echo "Connecting to Tailscale network..."
          # Servis çalıştığı için '&' kullanmaya gerek yok.
          tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-macos-runner-$GITHUB_RUN_ID
          
          # Tailscale IP almasını bekleme
          TS_IP=""
          echo "Waiting for Tailscale IP assignment..."
          for i in {1..15}; do
              TS_IP=$(tailscale ip -4 2>/dev/null)
