name: VNC Session on macOS (Ventura)

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    # DEĞİŞİKLİK BURADA: macOS-13 (Ventura) sürümü kullanılıyor.
    runs-on: macos-13
    timeout-minutes: 360 # 6 saat

    steps:
      - name: Set Password for Existing Runner User
        run: |
          # Workflow zaten 'runner' kullanıcısı olarak çalışıyor. Bu kullanıcıyı kullanacağız.
          VNC_USER="runner"
          echo "VNC_USER=${VNC_USER}" >> $GITHUB_ENV

          # Mevcut 'runner' kullanıcısı için güvenli ve rastgele bir şifre oluştur.
          VNC_PASS=$(openssl rand -base64 16)
          echo "VNC_PASS=${VNC_PASS}" >> $GITHUB_ENV

          # 'runner' kullanıcısının şifresini ayarla. 
          sudo dscl . -passwd /Users/$VNC_USER "$VNC_PASS"
          
          echo "Password for user '$VNC_USER' has been set successfully."

      - name: Enable VNC (Screen Sharing)
        run: |
          # VNC'yi etkinleştir ve 'runner' kullanıcısına tüm izinleri ver.
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
              -activate -configure -access -on \
              -users ${{ env.VNC_USER }} -privs -all \
              -restart -agent -menu
          echo "VNC service enabled for user '${{ env.VNC_USER }}'."

      - name: Install and Start Tailscale
        run: |
          # Homebrew ile Tailscale'i kur.
          brew install tailscale
          
          # Tailscale servisini başlat.
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-macos-${{ github.run_id }} --accept-routes

      - name: Get Tailscale IP
        run: |
          # Tailscale'in IP ataması için bekle.
          TS_IP=""
          for i in {1..10}; do
            TS_IP=$(tailscale ip -4)
            if [ -n "$TS_IP" ]; then
              echo "Tailscale IP address acquired: $TS_IP"
              break
            fi
            echo "Waiting for Tailscale IP... ($i/10)"
            sleep 5
          done

          if [ -z "$TS_IP" ]; then
            echo "::error::Could not get Tailscale IP address."
            exit 1
          fi
          
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Maintain Connection
        run: |
          echo ""
          echo "=== VNC CONNECTION DETAILS ==="
          echo "Server Address: ${{ env.TAILSCALE_IP }}"
          echo "Username      : ${{ env.VNC_USER }}"
          echo "Password      : ${{ env.VNC_PASS }}"
          echo "Note: Use any VNC client (e.g., RealVNC, TightVNC)."
          echo "From a Mac, use Finder > Go > Connect to Server (vnc://${{ env.TAILSCALE_IP }})"
          echo "==============================="
          echo ""
          
          # Runner'ı aktif tutmak için sonsuz döngü.
          while true; do
            echo "[$(date)] VNC session is active. Cancel the workflow to terminate."
            sleep 300
          done
